### ISSUE TITLE
Unit test workflow 

### ISSUE THREAD

**Issue by jonathanrodgz** [LuisEnMarroquin/json-as-xlsx#31]
It would be nice to add a workflow that triggers unit tests to avoid regressions.

```yml
name: Unit Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
```

Example [github-developer/javascript-action](https://github.com/github-developer/javascript-action/blob/963a3b9a9c662fd499419a240ed8c49411ff5add/.github/workflows/test.yml)

**Comment by LuisEnMarroquin** [comment]
Thanks added it to PRs on `main` and `develop`

```yml
name: PRD

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - name: Build JavaScript file
        run: npm run build
```
